### ISSUE TITLE
After connecting Mapbox account, custom styles are not displayed

### ISSUE THREAD

**Issue by giap** [eddiesigner/sketch-map-generator#47]
I input my token and username, however the styles that are displayed when I try to generate a map are not my personal styles, I am not sure if I am doing something wrong or it doesn't work?

**Comment by eddiesigner** [comment]
Did you follow these steps https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-create-a-token-to-use-your-own-Mapbox-styles ?

Please make sure your token has the secret scope `STYLES:LIST` enabled.

How long ago did you create the token? It takes up one hour to get the styles after created.

Also maybe you'll need to mark your styles as public and then wait one hour to see the changes reflected.

**Comment by giap** [comment]
I hadn't followed those steps, I went over the main page, but did not find this. Thanks a lot! This plugin is amazing :)

PS: I am wondering whether it would be possible to generate a map without the Mapbox logo and the OpenStreetMap watermarks at the bottom? I don't see all the Mapbox services featuring these two elements and it would be nice to be able to have the clean map.

**Comment by eddiesigner** [comment]
Sadly that's not possible, you must display the Mapbox wordmark and text attribution according to this page: https://docs.mapbox.com/help/how-mapbox-works/attribution/

As an option, you can still crop the layer to remove those logos ;)

**Comment by giap** [comment]
Thank you for your answer, cheers! 
All best

**Comment by Brandon-P** [comment]
I followed the steps but I get a list of maps that don't reflect what I see in mapbox studio. Is there some sort of cache I need to clear? Preview doesn't seem to work when a mapbox token has been saved. I don't know if that's known or not.

<img width="186" alt="Screen Shot 2019-08-13 at 8 50 10 PM" src="https://user-images.githubusercontent.com/3459191/62993405-04beaa00-be0c-11e9-9fe6-8f24ffdd5aa5.png">
<img width="66" alt="Screen Shot 2019-08-13 at 8 50 24 PM" src="https://user-images.githubusercontent.com/3459191/62993406-05574080-be0c-11e9-8347-2b39c83215a3.png">

**Comment by eddiesigner** [comment]
@Brandon-P Please download the latest version (3.5.2) where the issue with the preview is fixed, although from now on you'll need your public token as well ([more info here](https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-get-your-Mapbox-tokens)).

Now, regarding the problem with the list of styles, you have to make sure that the secret token belongs to the username you entered, also note that if you created one or more styles shortly before or shortly after installing the plugin, it may take up to an hour for them to appear in the list.

What styles do you see if you enter this url in your browser? https://api.mapbox.com/styles/v1/YOUR_USERNAME_HERE?access_token=YOUR_SECRET_TOKEN_HERE

If the styles don't match, then maybe some of them are unpublished or there is some issue with the cache from Mapbox. The plugin obtains the styles using that url, that means that if you see something weird there, you should check your style settings or try to contact Mapbox support directly.

**Comment by phillito** [comment]
Hey (awesome plugin btw) we are also experiencing a problem with the map preview after connecting our own Google Maps API key. The preview doe not load (with or without a custom style) but the map generates successfully.

**Comment by eddiesigner** [comment]
@phillito did you follow these steps? https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-generate-a-Google-Maps-key

Pay special attention to step number two.

**Comment by phillito** [comment]
@eddiesigner we have regenerated the API key but still no luck. Could it be because we are using an Enterprise account? I see someone else has raised the same issue, so happy to continue in that thread.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if you think is necessary.
